console.log("-------------- FIRST ASSIGNMENT ---------------");
var name1='sweety';
var name2='cutie';
console.log("Before Swapping:","name1-",name1,"& name2-",name2);
var temp;
temp=name1;
name1=name2;
name2=temp;
console.log("After Swapping:","name1-",name1,"& name2-",name2);
console.log("================================================");
 var num1=100,num2=200,num3=300;
 console.log("Before Swapping:num1=",num1,"num2=",num2,"num3=",num3);
var temp;
temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log("After Swapping:num1=",num1,"num2=",num2,"num3=",num3);
console.log("================================================");