console.log("--------First Assignment----------");
var myFullName;
console.log("Before Initialization:",myFullName);
myFullName='Prathemsh Patil';
console.log("After Initialization:",myFullName);
myFullName='Prathmesh Maruti Patil';
console.log("After Updatation:",myFullName);
console.log("-------------------***----------------------");
var myLove='I Love Only JS';
console.log("myLove:",myLove);
console.log("-------------------***----------------------");
firstName="Prathmesh";
lastName="Patil";
age=24;
address="Kolhapur";
pinCode=416211;
gender="Male";
itMarried=false;

console.log("firstName:",firstName);
console.log("lastName:",lastName);
console.log("age:",age);
console.log("address:",address);
console.log("pinCode:",pinCode);
console.log("gender:",gender);
console.log("itMarried:",itMarried);
