console.log(`================= Assignment 2 ===============`);
var n1 = 4;
var result = n1 - true;
console.log(`4 - true`);
console.log(`The Result is: ${result}`);
console.log(`Boolean true  is Indicates value 1 so here Substraction is Performed.`);
console.log(`-------------------------------------------`);
var n1 = 4;
var result = n1 + true;
console.log(`4 + true`);
console.log(`The Result is: ${result}`);
console.log(`Boolean true  is Indicates value 1 so here Addition is Performed.`);
console.log(`-------------------------------------------`);
var n1 = 4;
var result = n1 + false;
console.log(`4 + false`);
console.log(`The Result is: ${result}`);
console.log(`Boolean false  is Indicates value 0 so here Addition is Performed.`);
console.log(`-------------------------------------------`);