console.log(`================= Assignment 4 ===============`);
var result = 0 == ' ';
console.log(`0 == ' ' Result is: ${result} (Space is Implicitly converted into the Number:)`);
console.log(`---------------------------------------------------------------------------`);
var result = 0 == '0';
console.log(`0 == '0' Result is: ${result} ('0' String is Implicitly converted into the Number:)`);
console.log(`----------------------------------------------------------------------------`);
var result = 0 == false;
console.log(`0 == false Result is: ${result} (False is Implicitly converted into the Numbers:)`);
console.log(`----------------------------------------------------------------------------`);
var result = null == undefined;
console.log(`null == undefined Result is: ${result} (Both values are True...)`);
console.log(`----------------------------------------------------------------------------`);
var result = 1 == [1];
console.log(`1 == [1] Result is: ${result} (Object 1 is Implicitly converted into the Number:)`);
console.log(`----------------------------------------------------------------------------`);
var result = 1 == true;
console.log(`1 == true Result is: ${result} (True is Implicitly converted into the Numbers:)`);
console.log(`----------------------------------------------------------------------------`);
var result = 1 == '1';
console.log(`1 == '1' Result is: ${result} (1 is implicitly converted into the Number...)`);
console.log(`----------------------------------------------------------------------------`);