console.log(`================= Assignment 1 ===============`);
var str = '3';
var num = 2;
var result = str + num;
console.log(`'3' + 2`);
console.log(`The Result is= ${result}`);
console.log(`Type of Result = ${typeof result}`);
console.log(`2 is a Number implicitly converted to String..`);
console.log(`-------------------------------------------`);
console.log(`'3' + true`);
var num  = '3';
var bool = true;
var result = num + bool;
console.log(`The Result is= ${result}`);
console.log(`Type of Result = ${typeof result}`);
console.log(`true is a Boolean Value implicitly converted to String..`);
console.log(`-------------------------------------------`);
console.log(`'3' + undefined`);
var num  = '3';
var un = undefined;
var result = num + un;
console.log(`The Result is= ${result}`);
console.log(`Type of Result = ${typeof result}`);
console.log(`undefined Value implicitly converted to String..`);
console.log(`-------------------------------------------`);
console.log(`'3' + null`);
var num  = '3';
var nun = null;
var result = num + nun;
console.log(`The Result is= ${result}`);
console.log(`Type of Result = ${typeof result}`);
console.log(`null Value implicitly converted to String..`);
console.log(`-------------------------------------------`);