var bankName;
console.log("before Initialize value:",bankName);
console.log("before Initialize value typeOf:",typeof(bankName));
bankName="SBI Bank";
console.log("After Initialize value:",bankName);
console.log("After Initialize value typeOf:",typeof(bankName));
console.log("-------------------***----------------------");
var marks='90%';
console.log("marks:",marks);
console.log("data type of Marks:",typeof(marks));
console.log("-------------------***----------------------");
var isWorking;
console.log("before Initialize value:",isWorking);
console.log("before Initialize value typeOf:",typeof(isWorking));
isWorking=true;
console.log("After Initialize value:",isWorking);
console.log("After Initialize value typeOf:",typeof(isWorking));
console.log("-------------------***----------------------");
var totalCount="Hundred and Seven";
console.log("Value is:",totalCount);
console.log("Type of totalCount:",typeof(totalCount));
totalCount=107;
console.log("Value is:",totalCount);
console.log("Type of totalCount:",typeof(totalCount));