const arrayFruit = ["Banana", "Orange", "Apple", "Mango", "Water Melon"];
console.log(`------------------------- Step 1 -------------------------`);
var first = arrayFruit[0];
console.log(`First Element in Array is: ${first}`);
var first1 = arrayFruit[arrayFruit.length-1];
console.log(`Last Element in Array is: ${first1}`);
console.log(`------------------------- Step 2 -------------------------`);
arrayFruit.splice(0,0,"Papaya");
console.log(`Add Element at First Position: ${arrayFruit}`);
console.log(`------------------------- Step 3 -------------------------`);
let removedElement = arrayFruit.pop(3);
console.log(arrayFruit);
console.log(`Remove Element: ${removedElement}`);
console.log(`------------------------- Step 4 -------------------------`);
arrayFruit.push("Pineapple");
console.log(arrayFruit);
console.log(`------------------------- Step 5 -------------------------`);
arrayFruit.splice(3,0,"DragonFruit");
console.log(arrayFruit);
